import test from 'node:test';
import assert from 'node:assert/strict';
import { MAPS,WEAPONS,TICK,createMatch,createPlayer,resetPlayer,readyPlayer,stepMatch,cleanInput,movePlayer,rayWorld,castShot,floorAt } from '../src/shared.js';
const empty={extent:100,boxes:[],ramps:[]};
const control=(extra={})=>cleanInput({yaw:0,pitch:0,...extra});
function duel(){const m=createMatch();m.players=[createPlayer('a','A',0),createPlayer('b','B',1)];readyPlayer(m,m.players[0]);readyPlayer(m,m.players[1]);for(let i=0;i<181;i++)stepMatch(m,{});return m;}
test('room waits for two ready players, then starts countdown and live round',()=>{const m=createMatch(),a=createPlayer('a','A');m.players=[a];readyPlayer(m,a);assert.equal(m.phase,'waiting');const b=createPlayer('b','B',1);m.players.push(b);readyPlayer(m,b);assert.equal(m.phase,'countdown');for(let i=0;i<181;i++)stepMatch(m,{});assert.equal(m.phase,'live');});
test('forward and strafe align with center camera direction',()=>{const p=createPlayer('a','A');for(let i=0;i<60;i++)movePlayer(p,control({z:1}),empty,TICK);assert(p.p[2]<-6);assert.equal(p.p[0],0);const q=createPlayer('b','B');for(let i=0;i<60;i++)movePlayer(q,control({z:1,yaw:Math.PI/2}),empty,TICK);assert(q.p[0]>6);});
test('sprint -> slide -> slide jump retains momentum, with one air jump',()=>{const p=createPlayer('a','A');for(let i=0;i<60;i++)movePlayer(p,control({z:1,sprint:true}),empty,TICK);assert(Math.hypot(p.v[0],p.v[2])>11);movePlayer(p,control({z:1,slide:1}),empty,TICK);assert(p.slide>0);movePlayer(p,control({z:1,slide:1,jump:1}),empty,TICK);assert(p.v[1]>8);assert(Math.hypot(p.v[0],p.v[2])>15);movePlayer(p,control({jump:2,slide:1}),empty,TICK);assert.equal(p.jumps,2);const vy=p.v[1];movePlayer(p,control({jump:3,slide:1}),empty,TICK);assert(p.v[1]<vy);});
test('ramps are walkable on all maps and lead onto elevated platforms',()=>{for(const map of MAPS){const r=map.ramps[0],p=createPlayer('a','A');p.p=[r.x,0,r.z-r.d/2-1];for(let i=0;i<Math.ceil((r.d+3)/8*90);i++)movePlayer(p,control({z:-1}),map,TICK);assert(p.p[1]>=r.h-.1,`${map.id}: ${p.p}`);assert(p.ground);}});
test('walls stop movement and bridge underside does not push player sideways',()=>{const p=createPlayer('a','A');p.p=[0,0,6];for(let i=0;i<60;i++)movePlayer(p,control({z:1}),MAPS[0],TICK);assert(p.p[2]>=3.8);const q=createPlayer('q','Q');q.p=[4,0,4];for(let i=0;i<30;i++)movePlayer(q,control({z:1}),MAPS[2],TICK);assert(q.p[2]<1);assert.equal(q.p[0],4);});
test('raycast respects solid cover and exact ramp surfaces',()=>{assert(rayWorld([0,1.58,10],[0,0,-1],MAPS[0],100)<7);const r=MAPS[0].ramps[0];assert(rayWorld([r.x,r.h+1,r.z-8],[0,0,1],{boxes:[],ramps:[r]},16)===16);assert(rayWorld([r.x,1,r.z-8],[0,0,1],{boxes:[],ramps:[r]},16)<16);});
test('ADS center ray hits head, cover blocks targets',()=>{const a=createPlayer('a','A'),b=createPlayer('b','B');b.p=[0,0,-8];let h=castShot([0,1.58,0],[0,0,-1],empty,[a,b],'a',100);assert.equal(h.target,b);assert(h.head);h=castShot([0,1.58,10],[0,0,-1],MAPS[0],[a,b],'a',100);assert.equal(h.target,null);});
test('server rules consume ammo, enforce reload and firing cooldown',()=>{const m=duel(),p=m.players[0];p.p=[-12,0,12];p.cooldown=0;const inputs={a:control({fire:true}),b:control({yaw:Math.PI})};for(let i=0;i<60;i++)stepMatch(m,inputs);assert(p.ammo[0]>=16&&p.ammo[0]<=18);const count=p.ammo[0];stepMatch(m,{a:control({reload:true})});assert(p.reload>0);for(let i=0;i<30;i++)stepMatch(m,inputs);assert.equal(p.ammo[0],count);for(let i=0;i<100;i++)stepMatch(m,{a:control()});assert.equal(p.ammo[0],WEAPONS[0].ammo);});
test('exactly five round wins finish a match and both players must ready for rematch',()=>{const m=duel(),[a,b]=m.players;for(let round=1;round<=5;round++){assert.equal(m.phase,'live');a.p=[-12,0,12];b.p=[-12,0,4];a.weapon=2;a.cooldown=0;a.trigger=false;stepMatch(m,{a:control({fire:true,weapon:2,ads:true}),b:control({yaw:Math.PI})});assert.equal(b.hp,0);assert.equal(a.score,round);if(round<5){assert.equal(m.phase,'intermission');for(let i=0;i<400;i++)stepMatch(m,{});}}
  assert.equal(m.phase,'finished');assert.equal(m.winner,'a');readyPlayer(m,a);assert.equal(m.phase,'finished');readyPlayer(m,b);assert.equal(m.phase,'countdown');assert.equal(a.score,0);assert.equal(m.round,1);
});
test('timed rounds compare health; equal health is a draw without score',()=>{let m=duel();m.clock=.001;stepMatch(m,{});assert.equal(m.phase,'intermission');assert(m.players.every(p=>p.score===0));m=duel();m.players[1].hp=40;m.clock=.001;stepMatch(m,{});assert.equal(m.players[0].score,1);});
test('untrusted inputs reject nonfinite values and cannot specify damage or position',()=>{const i=cleanInput({x:Infinity,z:100,yaw:NaN,pitch:999,weapon:999,p:[99,99,99],damage:1000,fire:'yes'});assert.equal(i.x,0);assert.equal(i.z,1);assert.equal(i.yaw,0);assert.equal(i.weapon,WEAPONS.length-1);assert.equal(i.fire,false);assert.equal(i.damage,undefined);assert.equal(i.p,undefined);});
test('all spawn positions have clear ground',()=>{for(const map of MAPS)for(const spawn of map.spawns)assert.equal(floorAt(map,spawn[0],spawn[2]),0);});
test('quick fire press between packets is delivered once, even after release',()=>{const m=duel(),p=m.players[0];p.weapon=2;p.cooldown=0;stepMatch(m,{a:control({weapon:2,fire:false,fireId:1})});assert.equal(p.ammo[2],4);for(let i=0;i<100;i++)stepMatch(m,{a:control({weapon:2,fire:false,fireId:1})});assert.equal(p.ammo[2],4);stepMatch(m,{a:control({weapon:2,fire:false,fireId:2})});assert.equal(p.ammo[2],3);});

